title: 개발일지
description: HONG YOON YOUNG's OPEN CV
author: Hong Yoon Young
github: https://github.com/yoonyoung97
about: 부산대학교 재학중. AI 및 서비스 개발 
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "www.linkedin.com/in/yoonyoung-hong-744684196"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/yoonyoung97"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://yoonyoung97.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
